#!/usr/bin/env bash

# Import helpers function
source helpers

ask_choice "Install on Raspian or on Debian/Ubuntu ? " 0 Raspbian Debian/Ubuntu
if [[ $BOTASK_ANSWER == 0 ]]; then
	"${path_of_this_file}/./installRasp"
else
	"${path_of_this_file}/./installDebian"
fi
